In [ ]:
2 types of data
Qualitative
Quantitaive

SyntaxError: invalid syntax (2339437993.py, line 1)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/CDAC_DataBook.xlsx", sheet_name="ERPData")
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [ ]:
x1 = df.MaterialID

In [ ]:
len(np.unique(x1))

6

In [ ]:
np.unique(x1, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [ ]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

In [ ]:
df1 = x1.value_counts().reset_index()
df1

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [ ]:
df1['prop'] = df1['count']/sum(df1['count'])
df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    GCVB-79      5  0.10
5    LXCV-21      5  0.10

In [ ]:
df1['pct']=df1['prop']*100
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [ ]:
x2 = np.array([3,7,5,2,3,8])
np.cumsum(x2)

array([ 3, 10, 15, 17, 20, 28])

In [ ]:
df1['cumpct']=np.cumsum(df1['pct'])
df1

  MaterialID  count  prop   pct  cumpct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

In [ ]:
# central teendency = mean, mmedian mode
# dispersion or variation or spread-range interquarttile range, variance and standard deviation
# shape skewnness and kurtoisis

**day 6**

In [ ]:
df = pd.read_excel("/content/CDAC_DataBook.xlsx", sheet_name="faithful")
df.head()

   eruptions  waiting
0      3.600       79
1      1.800       54
2      3.333       74
3      2.283       62
4      4.533       85

In [ ]:
101/2

50.5

In [ ]:
x1 = df.eruptions

In [ ]:
sum(x1)/len(x1)

3.487783088235294

In [ ]:
len(x1)

272

In [ ]:
range, interquearter range, standard deviation

In [ ]:
from scipy import stats

In [ ]:
stats.mode(x1)

ModeResult(mode=np.float64(1.867), count=np.int64(8))

In [ ]:
len(np.where(x1==1.867)[0])

8

In [ ]:
from collections import Counter

In [ ]:
Counter(x1).most_common

<bound method Counter.most_common of Counter({1.867: 8, 4.5: 8, 1.833: 7, 4.7: 6, 1.75: 6, 4.8: 6, 4.0: 6, 4.533: 5, 4.083: 5, 3.833: 5, 4.333: 5, 3.6: 4, 1.8: 4, 4.35: 4, 4.25: 4, 1.883: 4, 2.0: 4, 4.167: 4, 4.417: 4, 4.6: 4, 4.15: 4, 4.583: 4, 3.917: 3, 1.967: 3, 2.017: 3, 4.567: 3, 2.1: 3, 4.633: 3, 1.817: 3, 1.983: 3, 4.933: 3, 2.2: 3, 4.367: 3, 4.233: 3, 4.45: 3, 3.333: 2, 2.167: 2, 3.85: 2, 4.433: 2, 4.3: 2, 4.467: 2, 4.033: 2, 4.833: 2, 2.233: 2, 4.133: 2, 4.1: 2, 4.067: 2, 3.95: 2, 4.817: 2, 4.667: 2, 4.9: 2, 1.783: 2, 3.767: 2, 1.917: 2, 2.033: 2, 2.4: 2, 3.567: 2, 3.5: 2, 1.933: 2, 2.083: 2, 2.417: 2, 2.25: 2, 4.267: 2, 4.117: 2, 1.85: 2, 4.283: 2, 2.283: 1, 2.883: 1, 1.95: 1, 4.2: 1, 1.6: 1, 3.45: 1, 3.067: 1, 3.367: 1, 4.783: 1, 3.317: 1, 4.716: 1, 1.733: 1, 4.883: 1, 3.717: 1, 1.667: 1, 4.317: 1, 4.4: 1, 2.067: 1, 5.067: 1, 3.883: 1, 2.633: 1, 4.517: 1, 3.75: 1, 2.483: 1, 4.05: 1, 4.85: 1, 3.683: 1, 4.733: 1, 2.3: 1, 1.7: 1, 2.317: 1, 2.617: 1, 2.267: 1, 4.65: 1, 2.8: 1, 4.383: 1, 3.733: 1, 5.1: 1, 5.033: 1, 3.967: 1, 2.367: 1, 5.0: 1, 4.617: 1, 2.183: 1, 3.966: 1, 4.366: 1, 2.383: 1, 3.417: 1, 4.483: 1, 4.55: 1, 4.183: 1, 2.217: 1, 2.333: 1, 2.35: 1, 2.9: 1, 2.133: 1, 3.817: 1, 4.767: 1, 4.75: 1, 2.15: 1})>

In [ ]:
max(x1) - min(x1)

3.4999999999999996

In [ ]:
np.ptp(x1)

np.float64(3.4999999999999996)

In [ ]:
iqr = np.percentile(x1,75) - np.percentile(x1,25)
iqr

np.float64(2.2915)

In [ ]:
np.var(x2)

np.float64(4.888888888888888)

In [ ]:
np.std(x2)

np.float64(2.2110831935702664)

In [ ]:
np.var(x2, ddof=1)

np.float64(5.866666666666665)

In [ ]:
np.std(x2, ddof=1)

np.float64(2.422120283277993)

In [ ]:
from scipy.stats import binom

In [ ]:
problem statement

In [ ]:
binom.pmf(10,15,0.7) #for exact output equal to 10 out of 15

np.float64(0.20613038097752098)

In [ ]:
binom.cdf(10,15,0.7) # used for finding out probabilty upto perticular values

np.float64(0.4845089407731571)

In [ ]:
1 - binom.cdf(10,15,0.7) #minimum probability starting from 9 AND further

np.float64(0.5154910592268429)

In [ ]:
from scipy.stats import poisson

In [ ]:
poisson.pmf(12,15)

np.float64(0.08285923436864541)

In [ ]:
poisson.cdf(12,15)

np.float64(0.2676110333925769)

In [ ]:
1 - poisson.cdf(11,15)

np.float64(0.8152482009760685)

In [ ]:
from scipy.stats import norm, t

In [ ]:
norm.cdf(14,16,2.3)

np.float64(0.19226902649831168)

In [ ]:
1 - norm.cdf(14,16,2.3)

np.float64(0.8077309735016883)

In [ ]:
norm.sf(14,16,2.3)

np.float64(0.8077309735016883)

**Day 7**

In [ ]:
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t

In [ ]:
poisson.pmf(5,7)

np.float64(0.1277166682922895)

In [ ]:
norm.cdf(43,45,2.8)

np.float64(0.2375252620269765)

In [ ]:
z = (43-45)/2.8
z

-0.7142857142857143

In [ ]:
norm.cdf(z, 0,1)

np.float64(0.2375252620269765)

In [ ]:
# Exponential Distrubutions

43.845

In [ ]:
from scipy.stats import expon

In [ ]:
expon.cdf(100, scale=43.8)

np.float64(0.898032895521957)

0.0625

In [ ]:
#prob of event occurs 50 times in 45 days
45*8/30

12.0

In [ ]:
expon.cdf(8, scale=12)

np.float64(0.486582880967408)