In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import scipy
from scipy import stats
from scipy.stats import binom, poisson, norm, t
from scipy.stats import expon

In [ ]:
norm.cdf(55,60,5)

np.float64(0.15865525393145707)

In [ ]:
norm.cdf(-1)

np.float64(0.15865525393145707)

In [ ]:
norm.ppf(0.1586)  # area taken is always from left side in PPF

np.float64(-1.0002283757327086)

In [ ]:
norm.cdf(0.15)

np.float64(0.5596176923702425)

In [ ]:
norm.ppf(0.5596176923702425)

np.float64(0.14999999999999997)

In [ ]:
norm.ppf(.025)

np.float64(-1.9599639845400545)

In [ ]:
norm.ppf(0.975)

np.float64(1.959963984540054)

In [ ]:
# n = 300
# sample mean - 1800
# pop SD = 70
# interval estimate as (95%) CL

In [ ]:
n = 300
Xbar = 1800
stdev = 70
cl = 0.95

In [ ]:
z = np.abs(norm.ppf((1-cl)/2))
z

np.float64(1.959963984540054)

In [ ]:
t = np.abs(t.ppf((1-cl)/2,n-1))

In [ ]:
t

np.float64(1.9679296690653618)

In [ ]:
low_est = Xbar - t*stdev/n**0.5
upper_est = Xbar + t*stdev/n**0.5

size = upper_est - low_est

In [ ]:
size

np.float64(15.906586138536113)

In [ ]:
stats.t.interval(cl,n-1,Xbar,stdev/n**0.5) #forula for same calculations

(np.float64(1792.046706930732), np.float64(1807.953293069268))

In [ ]:
# DAY 10

In [ ]:
df = pd.read_excel('/content/CDAC_DataBook.xlsx', sheet_name='faithful')

In [ ]:
erupt = df.eruptions

In [ ]:
xbar = np.mean(erupt)
n = len(erupt)
sd = np.std(erupt,ddof=1)

In [ ]:
import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

In [ ]:
ssw.ztest(erupt, value=3.7  , alternative='smaller')

(np.float64(-3.06646147570652), np.float64(0.0010830435959524984))

In [ ]:
z = (xbar-3.7)/(sd/n**0.5)
z

np.float64(-3.066461475706521)

In [ ]:
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In [ ]:
z = (xbar - 3.53)/(sd/n**0.5)
z

np.float64(-0.6100198729369253)

In [ ]:
norm.cdf(z)

np.float64(0.2709243216144542)

In [ ]:
# second example
z = (xbar-3.37)/(sd/n**0.5)
z

np.float64(1.7019251649638614)

In [ ]:
norm.ppf(0.95)

np.float64(1.6448536269514722)

In [ ]:
1 - norm.cdf(z) # to find p value for right side

np.float64(0.044384698843295656)

In [ ]:
ssw.ztest(erupt, value=3.37,alternative='smaller') # to find P value (second  o/p)

(np.float64(1.7019251649638607), np.float64(0.9556153011567042))

In [ ]:
# thid example
# minimum waiting time is 75%
# mue should be greater than stats

In [ ]:
xbar = 1.645* sd/n**0.5
wait = df.waiting
xbar = np.mean(wait)
n = len(wait)
sd = np.std(wait, ddof= 1)

In [ ]:
z = (xbar - 75)/(sd/n**0.5)
z

np.float64(-4.977386527579323)

In [ ]:
norm.cdf(z)

np.float64(3.222427049500585e-07)

In [ ]:
xbar + 1.645*sd/n**0.5 # to find upperbound

np.float64(72.25305924622042)

In [ ]:
xbar

np.float64(70.8970588235294)

In [ ]:
ssw.ztest(wait, value=75, alternative='smaller')

(np.float64(-4.9773865275793225), np.float64(3.222427049500608e-07))

**smaller** will be replaced by **larger** keyword in right tail test
and if 2 test tail then alternative will be **two-sided**

In [ ]:
# 2 test tail

In [ ]:
df = pd.read_excel('/content/CDAC_DataBook.xlsx', sheet_name='faithful')

In [ ]:
df1 = df.iloc[20:60]

In [ ]:
df2 = df.iloc[120:170]

In [ ]:
erupt1 = df1.eruptions

In [ ]:
erupt2 = df2.eruptions

In [ ]:
np.mean(erupt1) # mean of erupt 2 is atleast 0.12 more than the mean of erupt1

np.float64(3.44745)

In [ ]:
np.mean(erupt2)

np.float64(3.4876399999999994)

In [ ]:
ssw.ztest(erupt2, erupt1,  value=0.12, alternative='smaller')

(np.float64(-0.3196536558502502), np.float64(0.3746154475542464))

-------------------------Day 11--------------------

In [ ]:
# paired t test

In [ ]:
before = np.array([12,14,10,9,8,13])

In [ ]:
after = np.array([11.8,9.7,11.3,8.2,7.2,12.3])

In [ ]:
# avg(before - after)>=2
# avg (before - after) < 2     left tail test

In [ ]:
d = (before - after)
d

NameError: name 'before' is not defined

In [ ]:
np.mean(d)

np.float64(0.9166666666666665)

In [ ]:
ssw.ttost_paired(before,after,low=2,upp=2)

(np.float64(0.8954696830206994),
 (np.float64(-1.4413160909218492),
  np.float64(0.8954696830206994),
  np.float64(5.0)),
 (np.float64(-1.4413160909218492),
  np.float64(0.10453031697930062),
  np.float64(5.0)))

In [ ]:
scipy.stats.ttest_1samp(before-after,popmean=2, alternative='less')

TtestResult(statistic=np.float64(-1.4413160909218492), pvalue=np.float64(0.10453031697930062), df=np.int64(5))

In [ ]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

In [ ]:
dfA = pd.DataFrame({'Col1':np.repeat('A',7),'Col2':np.random.randint(10,30,7)})
dfB = pd.DataFrame({'Col1':np.repeat('B',9),'Col2':np.random.randint(20,40,9)})
dfC = pd.DataFrame({'Col1':np.repeat('C',8),'Col2':np.random.randint(15,30,8)})
df = pd.concat([dfA,dfB,dfC])
df

  Col1  Col2
0    A    23
1    A    16
2    A    16
3    A    25
4    A    20
5    A    28
6    A    22
0    B    35
1    B    24
2    B    27
3    B    35
4    B    25
5    B    35
6    B    30
7    B    36
8    B    33
0    C    16
1    C    21
2    C    21
3    C    20
4    C    28
5    C    29
6    C    29
7    C    23

In [ ]:
mod1 = ols('Col2 ~ Col1',df).fit() #column 1 is factor col2 is response #ols ordinary least square
tbl = sm.stats.anova_lm(mod1)
print(tbl)

            df      sum_sq     mean_sq         F    PR(>F)
Col1       2.0  434.480159  217.240079  9.907183  0.000933
Residual  21.0  460.478175   21.927532       NaN       NaN

In [ ]:
print(pairwise_tukeyhsd(df.Col2, df.Col1))

NameError: name 'pairwise_tukeyhsd' is not defined

In [ ]:
df = pd.read_excel('/content/data_anova.xlsx')
df

   Col1  Col2
0     A    10
1     A    23
2     A    14
3     A    25
4     A    22
5     A    11
6     A    12
7     B    26
8     B    39
9     B    29
10    B    39
11    B    31
12    B    32
13    B    38
14    B    22
15    B    25
16    C    21
17    C    23
18    C    26
19    C    19
20    C    29
21    C    27
22    C    17
23    C    24

In [ ]:
df.index = np.arange(df.shape[0])

In [ ]:
grp1 = df.groupby('Col1')

In [ ]:
samp_mean = grp1.agg('mean')

In [ ]:
grand_mean = np.mean(df.Col2)

In [ ]:
sampA = df.loc[df['Col1'] == 'A', 'Col2']
sampB = df.loc[df['Col1'] == 'B', 'Col2']
sampC = df.loc[df['Col1'] == 'C', 'Col2']

In [ ]:
7*(samp_mean.loc['A'] - grand_mean)**2 + 9*(samp_mean.loc['B'] - grand_mean)**2 + 8*(samp_mean.loc['C'] - grand_mean)**2

Col2    842.849206
dtype: float64

In [ ]:
tbl = sm.stats.anova_lm(mod1)
print(tbl)

            df      sum_sq     mean_sq         F    PR(>F)
Col1       2.0  434.480159  217.240079  9.907183  0.000933
Residual  21.0  460.478175   21.927532       NaN       NaN

In [ ]:
sum((np.array(sampA) - np.array(samp_mean.loc['A']))**2) + sum((np.array(sampB) - np.array(samp_mean.loc['B']))**2) + sum((np.array(sampC) - np.array(samp_mean.loc['C']))**2)

np.float64(684.484126984127)

In [ ]:
zoo = [34,43,57,40,85,68,67,53,41,24,42,52]
supp=[1,1,1,1,2,2,2,2,3,3,3,3]
lake=["R","D","R","D","R","D","R","D","R","D","R","D"]
df=pd.DataFrame({'Resp':zoo,"Factor1":supp,"Factor2":lake})

In [ ]:
df.head()

   Resp  Factor1 Factor2
0    34        1       R
1    43        1       D
2    57        1       R
3    40        1       D
4    85        2       R

In [ ]:
model = ols('Resp~Factor1+Factor2',df).fit()

In [ ]:
res=sm.stats.anova_lm(model)

In [ ]:
print(res)

           df       sum_sq     mean_sq         F    PR(>F)
Factor2   1.0   176.333333  176.333333  0.543765  0.479659
Factor1   1.0    28.125000   28.125000  0.086730  0.775056
Residual  9.0  2918.541667  324.282407       NaN       NaN